# .readthedocs.yml

build:
  image: latest

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: WORC/doc/conf.py

python:
  version: 3.7
  install:
    - method: pip
    - requirements: requirements.txt
    - requirements: WORC/doc/requirements.txt
